name: Apple silicon

on: [push, workflow_dispatch]

jobs:
  test:

    strategy:
      fail-fast: false
    runs-on: [macos-14]
    
    steps:
    - uses: actions/checkout@v1
    - name: make test
      run: make test
