name: benchmark

on: [workflow_dispatch]
#  schedule:
#    # Run at 22:40 UTC on Monday
#    - cron:  '40 22 * * 1'

jobs:
  bench:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: make bench
      run: make bench
